const styles = {
  titleForm: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottom: '1px solid rgb(108, 167, 176)',
    height: '30px',
    maxWidth: '700px',
    fontFamily: 'Arial',
  },
  titleInput: {
    boxSizing: 'border-box',
    flex: '1 0 0%',
    outline: 'none',
    whiteSpace: 'normal',
    overflow: 'hidden',
    fontFamily: 'Arial',
    padding: '4px 4px 2px',
    border: 'none',
    color: 'rgb(0, 0, 0)',
    fontFamily: 'Arial',
    textAlign: 'right',
    fontSize: '21px',
    overflowWrap: 'break-word',
    fontWeight: '500',
  },
  title: {
    boxSizing: 'border-box',
    cursor: 'default',
    padding: '4px',
    border: 'none',
    color: 'rgb(108, 167, 176)',
    outline: 'none',
    textAlign: 'left',
    fontSize: '21px',
    display: 'inline',
    opacity: 1,
    zIndex: 1,
    fontFamily: 'Arial',
    fontWeight: '500',
  },
};

export default styles;